### ISSUE TITLE
Can't startup a sihas-canary after updated a HASS to 2022.4.7

### ISSUE THREAD

**Issue by sungokay** [cmsong-shina/sihas-canary#1]
Hi,

I had updated a sihas-canary to 1.1.2 but can't setup it with a below error message.
I think this problem is caused by changing setup_platform to async_setup_entry.
Would you mind check this case?

Thanks
SO

```
Apr 26 16:20:40 raspberrypi hass[15843]: 2022-04-26 16:20:40 ERROR (MainThread) [homeassistant.components.sensor] The sihas_canary platform for the sensor integration does not support platform setup. Please remove it from your config.
Apr 26 16:20:40 raspberrypi hass[15843]: 2022-04-26 16:20:40 ERROR (MainThread) [homeassistant.components.sensor] The sihas_canary platform for the sensor integration does not support platform setup. Please remove it from your config.

```

https://github.com/cmsong-shina/sihas-canary/blob/71882111abdc014d8bee62ca8b58074086742cb4/sensor.py#L154

**Comment by cmsong-shina** [comment]
Hi sungokay,

Check your `configuration.yaml` and remove information about this integration.
Now we use zeroconfig instead writing configuration file manually.
REAME file is not updated yet, so check [this page](https://sihas.notion.site/HomeAssistant-1385c75ce8b94e1aa812b70bb6e727c3).

**Comment by sungokay** [comment]
I had removed the configuration from configuration.yaml and added via zeroconfig. After that, the problem had been solved.
Thanks
SO
