### ISSUE TITLE
Home Assistant 경고 메시지

### ISSUE THREAD

**Issue by Murianwind** [cmsong-shina/sihas-canary#13]
HA Core 2025.01에 예정된 변경사항에 대한 경고메시지에 대해 업데이트 해주시면 감사하겠습니다.

Logger: homeassistant.components.climate.const
Source: helpers/deprecation.py:204
Integration: 공조기기 (documentation, issues)
First occurred: 08:11:06 (11 occurrences)
Last logged: 08:11:06

HVAC_MODE_COOL was used from sihas, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.COOL instead, please create a bug report at https://github.com/cmsong-shina/sihas-canary/issues
HVAC_MODE_DRY was used from sihas, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.DRY instead, please create a bug report at https://github.com/cmsong-shina/sihas-canary/issues
HVAC_MODE_FAN_ONLY was used from sihas, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.FAN_ONLY instead, please create a bug report at https://github.com/cmsong-shina/sihas-canary/issues
HVAC_MODE_HEAT was used from sihas, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please create a bug report at https://github.com/cmsong-shina/sihas-canary/issues
HVAC_MODE_OFF was used from sihas, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please create a bug report at https://github.com/cmsong-shina/sihas-canary/issues

-----

Logger: homeassistant.components.cover
Source: helpers/deprecation.py:204
Integration: 여닫이 (documentation, issues)
First occurred: 08:11:06 (8 occurrences)
Last logged: 08:11:06

SUPPORT_CLOSE was used from sihas, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.CLOSE instead, please create a bug report at https://github.com/cmsong-shina/sihas-canary/issues
SUPPORT_OPEN was used from sihas, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.OPEN instead, please create a bug report at https://github.com/cmsong-shina/sihas-canary/issues
SUPPORT_SET_POSITION was used from sihas, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.SET_POSITION instead, please create a bug report at https://github.com/cmsong-shina/sihas-canary/issues
SUPPORT_STOP was used from sihas, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.STOP instead, please create a bug report at https://github.com/cmsong-shina/sihas-canary/issues

-----

Logger: homeassistant.components.sensor
Source: helpers/deprecation.py:204
Integration: 센서 (documentation, issues)
First occurred: 08:10:44 (10 occurrences)
Last logged: 08:11:06

STATE_CLASS_MEASUREMENT was used from sihas, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.MEASUREMENT instead, please create a bug report at https://github.com/cmsong-shina/sihas-canary/issues
STATE_CLASS_TOTAL was used from sihas, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.TOTAL instead, please create a bug report at https://github.com/cmsong-shina/sihas-canary/issues
STATE_CLASS_TOTAL_INCREASING was used from sihas, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.TOTAL_INCREASING instead, please create a bug report at https://github.com/cmsong-shina/sihas-canary/issues

**Comment by sungokay** [comment]
I had met a same problem after updated to 2024.1.2.

Thanks
SungOk

**Comment by sungokay** [comment]
Maybe. This problem is caused by a below site.

https://developers.home-assistant.io/blog/2023/12/19/constant-deprecation

SO

**Comment by cmsong-shina** [comment]
1.6.2b0에서 작업 중 입니다. 한번 업데이트 해보시겠어요?

[Enable beta for a repository | HACS](https://hacs.xyz/docs/faq/beta/)

**Comment by Murianwind** [comment]
업데이트 후

Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 11:04:20 (23 occurrences)
Last logged: 11:05:02

DEVICE_CLASS_POWER was used from sihas, this is a deprecated constant which
will be removed in HA Core 2025.1. Use SensorDeviceClass.POWER instead,
please create a bug report at
https://github.com/cmsong-shina/sihas-canary/issues
DEVICE_CLASS_POWER_FACTOR was used from sihas, this is a deprecated
constant which will be removed in HA Core 2025.1. Use
SensorDeviceClass.POWER_FACTOR instead, please create a bug report at
https://github.com/cmsong-shina/sihas-canary/issues
DEVICE_CLASS_VOLTAGE was used from sihas, this is a deprecated constant
which will be removed in HA Core 2025.1. Use SensorDeviceClass.VOLTAGE
instead, please create a bug report at
https://github.com/cmsong-shina/sihas-canary/issues

이런 메시지가 출력됩니다.

-----
Murian Song

SW Testing Evangelist & Consultant / TOC Evangelist & Consultant

Blog: http://murianwind.blogspot.com

Twitter: http://twitter.com/murianwind

Facebook: http://www.facebook.com/murianwind


2024년 1월 9일 (화) 오전 10:22, cmsong-shina ***@***.***>님이 작성:

**Comment by cmsong-shina** [comment]
> Contributor

v1.6.2b1로 수정했습니다.

**Comment by Murianwind** [comment]
에러 로그가 모두 해결되었습니다.

수정해주셔서 감사합니다.

새해 복 많이 많이 받으세요.

^^

-----
Murian Song

SW Testing Evangelist & Consultant / TOC Evangelist & Consultant

Blog: http://murianwind.blogspot.com

Twitter: http://twitter.com/murianwind

Facebook: http://www.facebook.com/murianwind


2024년 1월 9일 (화) 오후 1:05, cmsong-shina ***@***.***>님이 작성:

**Comment by cmsong-shina** [comment]
제보해 주셔서 감사합니다. 수정 사항은 HA Core 하위 호환성을 검토하고 정식으로 릴리즈하겠습니다.
