### ISSUE TITLE
BCM 제품의 "운전모드" (실내 / 온돌 / 온수) 관리 기능 지원

### ISSUE THREAD

**Issue by Hardtack** [cmsong-shina/sihas-canary#16]
안녕하세요. 시하스 BCM-300 제품을 Home Assistant에 연동하여 잘 사용하고 있습니다.

기본적인 연동 기능은 만족하며 사용하고 있습니다만, 운전모드 "실내", "온돌", "온수" 기능 컨트롤을 HA에서 할 수 없어 아쉬움이 많습니다.
해당 기능이 지원될수 있을지 건의드리며, 예정에 있는지도 궁금합니다.

**해당 기능의 필요성**

- 온수전용 상태에선 HA에서 온도 조절을 하더라도 반영이 되지 않음
- 실내 / 온돌 모드에서 설정 온도 기준이 달라지는데 현재 모드를 알기 어려워 자동화에 활용하기 어려움

**Comment by cmsong-shina** [comment]
몇 번 추가하려고 시도해봤는데, 몇 가지 어려운 점이 있어서 아직까지 추가를 못하고 있습니다.

우선은 온수의 온도가 어떤 건 온도고, 어떤 건 2단계고, 어떤 건 3단계고 이렇게 파편화가 심합니다.

엣지 드라이버의 경우 여러 디바이스 프로필을 만들고 추가 할 때 적절하게 선택해서 장치를 추가하는데, HA의 경우 장치 추가도 한번에 못하고 여러 엔티티에서 핸들링 해야하다보니 어려운점이 있습니다.

간간히 보고는 있는데 추가가 성공할지 어떨지는 말씀드리기 힘듭니다.
