### ISSUE TITLE
async_setup_platforms 지원 중단

### ISSUE THREAD

**Issue by Murianwind** [cmsong-shina/sihas-canary#3]
Home Assistant 를 2023.2.0으로 업데이트하면 아래와 같은 메시지가 출력됩니다.

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 08:15:46 (2 occurrences)
Last logged: 08:15:51

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for sihas_canary using this method at custom_components/sihas_canary/__init__.py, line 26: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

-----

현재 환경은 아래와 같습니다.

Home Assistant 2023.2.0
Supervisor 2023.01.1
Operating System 9.5
Frontend 버전: 20230201.0 - latest

스마트 전력미터 PMM-300-W/Z 단상형을 사용하고 있습니다.

-----
그리고 업데이트 해주실 때 HA의 통합구성요소에 기기로 등록되도록 업데이트 해주시면 좋겠습니다.

https://cafe.naver.com/koreassistant/10588

이런 식으로 지금은 사용자들이 수정해서 사용중인데.. 정식으로 지원되면 좋겠습니다.

변경 사항이 있을 때 쉽게 업데이트하고 관리할 수 있도록 시하스 컴포넌트를 HACS에서 설치하고 통합구성요소에서 기기록 등록해서 관리할 수 있었으면 좋겠습니다.

개인 개발자들도 지원할 수 있는 부분이기 때문에 시하스도 가능하다고 생각합니다.

**Comment by cmsong-shina** [comment]
제보 감사합니다. 요청 주신 사항은 검토 후 적용해보도록 하겠습니다.

**Comment by cmsong-shina** [comment]
@Murianwind
그런데 HA의 통합구성요소에 기기로 등록하게되면 어떤 이점이 있나요?

**Comment by Murianwind** [comment]
> @Murianwind 그런데 HA의 통합구성요소에 기기로 등록하게되면 어떤 이점이 있나요?

![image](https://user-images.githubusercontent.com/6447460/216246658-772572ec-3a8f-45b1-a50c-4c4921224701.png)

스크린샷 처럼 HA에서 관련 센서들을 하나로 묶어서 일목요연하게 관리할 수 있습니다.

**Comment by Murianwind** [comment]
예를 들면 HACS에 네이버 날씨라는 개인 개발자가 만든 컴포넌트가 있습니다. HACS에 컴포넌트가 등록되면 업데이트를 원클릭을 진행할 수 있어서 사용자는 굉장히 편리해집니다.

그리고 HACS에 등록된 컴포넌트가 기기 등록이 되면

![image](https://user-images.githubusercontent.com/6447460/216247122-ee49bc34-7c0a-49d8-847f-20587912f472.png)

처럼 관련 센서를 하나로 관리할 수 있습니다.

**Comment by cmsong-shina** [comment]
감사합니다.

기기 등록은 괜찮은 기능으로 보여집니다.
시간 나는 대로 작업하겠습니다.
